// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qudviteygcpzhkylhkmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1ZHZpdGV5Z2NwemhreWxoa21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NDgwNjUsImV4cCI6MjA4ODMyNDA2NX0.39eqHkflQekOgR3GvhU5373SGnJKo0saZYm4suSo2_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});